baseURL = "https://LogimexInternational.github.io/"
title = "Logimex International"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"
pluralizelisttitles = false

[menu]
[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Services"
    url  = "/services/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 3

[params]
    viewMorePostLink = "/blog/"
    author = "Logimex Group"
    defaultKeywords = ["logistics", "export"]
    mainSections = ["blog"]
    defaultDescription = "Logimex Group Corporate Website"
    
    # Date format (Required by theme)
    date_format = "January 2, 2006"

    # Style options: default, blue, green, marsala, pink, red, turquoise, violet
    style = "default"
    
    # Map (disabled to prevent errors)
    enableGoogleMaps = false

    # Footer
    copyright = "Copyright (c) 2026, Logimex International"
    
    # Branding
    disabled_logo = false
    logo_text = "Logimex International"
    logo = "img/logimex-logo.png"
    logo_small = "/img/logimex-logo-small.png"
    
    # Contact settings
    address = """<p><strong>Logimex International</strong><br>Jaipur, India</p>"""
    
    [params.topbar]
    enable = true
    text = "Welcome to Logimex International"


